-- add_wearer function
-- Exported from Supabase database

 CREATE OR REPLACE FUNCTION public.add_wearer(p_name text, p_safeloop_account_id uuid DEFAULT NULL::uuid, p_date_of_birth date DEFAULT NULL::date, p_emergency_contact_name text DEFAULT NULL::text, p_emergency_contact_phone text DEFAULT NULL::text)+
  RETURNS uuid                                                                                                                                                                                                                                         +
  LANGUAGE plpgsql                                                                                                                                                                                                                                     +
  SECURITY DEFINER                                                                                                                                                                                                                                     +
 AS $function$                                                                                                                                                                                                                                         +
 DECLARE                                                                                                                                                                                                                                               +
     wearer_id UUID;                                                                                                                                                                                                                                   +
     account_id UUID;                                                                                                                                                                                                                                  +
 BEGIN                                                                                                                                                                                                                                                 +
     -- Use provided account ID or get from current user                                                                                                                                                                                               +
     account_id := COALESCE(p_safeloop_account_id, get_user_safeloop_account_id());                                                                                                                                                                    +
                                                                                                                                                                                                                                                       +
     -- Create wearer                                                                                                                                                                                                                                  +
     INSERT INTO wearers (                                                                                                                                                                                                                             +
         safeloop_account_id,                                                                                                                                                                                                                          +
         name,                                                                                                                                                                                                                                         +
         date_of_birth,                                                                                                                                                                                                                                +
         emergency_contact_name,                                                                                                                                                                                                                       +
         emergency_contact_phone                                                                                                                                                                                                                       +
     )                                                                                                                                                                                                                                                 +
     VALUES (                                                                                                                                                                                                                                          +
         account_id,                                                                                                                                                                                                                                   +
         p_name,                                                                                                                                                                                                                                       +
         p_date_of_birth,                                                                                                                                                                                                                              +
         p_emergency_contact_name,                                                                                                                                                                                                                     +
         p_emergency_contact_phone                                                                                                                                                                                                                     +
     )                                                                                                                                                                                                                                                 +
     RETURNING id INTO wearer_id;                                                                                                                                                                                                                      +
                                                                                                                                                                                                                                                       +
     -- Create default wearer settings                                                                                                                                                                                                                 +
     INSERT INTO wearer_settings (wearer_id) VALUES (wearer_id);                                                                                                                                                                                       +
                                                                                                                                                                                                                                                       +
     RETURN wearer_id;                                                                                                                                                                                                                                 +
 END;                                                                                                                                                                                                                                                  +
 $function$                                                                                                                                                                                                                                            +
 ;

-- Grant permissions
GRANT EXECUTE ON FUNCTION add_wearer TO service_role;
GRANT EXECUTE ON FUNCTION add_wearer TO anon;
